# Generated by Django 4.1.7 on 2023-04-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_content',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
